export const FORMAT_ALIASES: Record<string, string> = {
  jpg: "jpeg",
  jpeg: "jpeg",
  tif: "tiff",
  tiff: "tiff",
  htm: "html",
  html: "html",
  markdown: "md",
  md: "md",
  yml: "yaml",
  yaml: "yaml",
  oga: "ogg",
  mpg: "mpeg",
  m2ts: "ts",
  mts: "ts",
  f4v: "flv",
  asciidoc: "adoc",
  texi: "texinfo",
  text: "txt",
  binary: "bin",
  midi: "mid",
  jsonl: "json",
  ndjson: "json",
};
